import React from "react";
import Navigation from "../Components/Navigation";
import Menu from "../Images/Menu_Projections.png";
import Projection from "../Images/Projections_page.png";
import Toolbar from "../Images/toolbar.svg";

function Instruction() {
  return (
    <div className="bg-white">
      <Navigation />
      <br />
      <br />
      <br />
      <h2 className="ml-3">Instructions</h2>
      <ol className="mt-3 ml-3 w-75">
        <li>Go to the projections page through the navigation menu.</li>
        <img src={Menu} alt="menu directions" className="right-alignment" />
        <li>
          If you would like to get the most recent data, click the refresh
          button.
        </li>
        <li>Select a country using the dropdown.</li>
        <li>Select the type of restriction measure and its duration.</li>
        <li className="w-50">
          To add additional intervals of restrictions click the + button or
          click the - button to delete the last interval.
        </li>
        <li>Click enter when you are satisfied with your choices.</li>
        <img
          src={Projection}
          alt="projection page"
          className="right-alignment-2"
        />
        <li className="w-50">
          To navigate along the graph click the zoom button to specify certain
          regions or use the pan button to move across the graph. To reset to
          the original graph, click the home button.
        </li>
        <img
          src={Toolbar}
          alt="matplotlib toolbar"
          className="right-alignment"
        />
      </ol>
      <h2 className="ml-3">Understanding the results</h2>
      <blockquote className="ml-5 mt-3 w-75">
        The results page will provide information regarding the basic
        reproduction number, effective reproduction number, maximum active
        cases, and data about the size of the susceptible, exposed, infectious,
        and recovered groups at the end of the intervals. Additionally, a graph
        will be provided to visualize peaks.
      </blockquote>
      <ul className="ml-5 w-75">
        <li>
          Basic reproduction number (R0): The average number of secondary cases
          generated by a single infected individual when intervention measures
          are not placed. A value below 1 indicates that the disease cannot
          spread effectively and will die out.
        </li>
        <li>
          Effective reproduction number (Rt): The average number of secondary
          cases generated by a single infected individual t days after
          intervention measures are placed. Once Rt &lt; 1 the disease will die
          out.
        </li>
        <li>
          Maximum active cases: Refers to the size of the peak in the infectious
          population.
        </li>
        <li>
          Susceptible population: People who are capable of becoming contagious.
        </li>
        <li>
          Exposed population: People who have been infected, however, they have
          yet to become infectious.
        </li>
        <li>Infectious population: People who are contagious.</li>
        <li>
          Recovered population: People who have developed immunity to the
          disease.
        </li>
      </ul>
    </div>
  );
}

export default Instruction;
